version: '3.3'

services:

  backendserver:
    networks:
      - chat
    container_name: backend
    
    image: aymen065/chat
    ports:
       - "80:8080"

    restart: on-failure
  

networks:
  chat: 
